
import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { AppDocument } from '../types';
import { FileText, UploadCloud, Search, Trash2, Download, Filter, FileStack, FileCheck, FileArchive, X, Plus, AlertCircle, CheckCircle2, DollarSign, RefreshCw, Eye, MoreVertical, Wand2, Package, Users, TrendingUp } from 'lucide-react';
import { jsPDF } from 'jspdf';

export default function Vault() {
  const { documents, addDocument, deleteDocument, user, transactions, inventory, staff, farms, crops, harvests, formatCurrency } = useApp();
  const [activeTab, setActiveTab] = useState<'ALL' | 'CONTRACT' | 'INVOICE' | 'RECEIPT' | 'REPORT' | 'DOWNLOAD'>('ALL');
  const [searchTerm, setSearchTerm] = useState('');
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [previewDoc, setPreviewDoc] = useState<AppDocument | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  
  const [newDoc, setNewDoc] = useState<Partial<AppDocument>>({ type: 'CONTRACT', category: 'General' });
  const [isUploading, setIsUploading] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const fileInputRef = React.useRef<HTMLInputElement>(null);

  const generateReport = (reportType: string) => {
    setIsGenerating(true);
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const now = new Date();

    // Header
    doc.setFillColor(10, 10, 26);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(0, 194, 255);
    doc.setFontSize(24);
    doc.text('NEXA AGRI', 15, 25);
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text(now.toLocaleDateString(), pageWidth - 15, 25, { align: 'right' });

    let reportTitle = '';
    let y = 55;

    if (reportType === 'financial') {
      reportTitle = 'Financial Summary Report';
      doc.setTextColor(50, 50, 50);
      doc.setFontSize(16);
      doc.text(reportTitle, 15, y);
      y += 15;
      const income = transactions.filter(t => t.type === 'INCOME').reduce((a, b) => a + b.amount, 0);
      const expense = transactions.filter(t => t.type === 'EXPENSE').reduce((a, b) => a + b.amount, 0);
      doc.setFontSize(11);
      doc.text(`Total Income: ${formatCurrency(income)}`, 15, y); y += 8;
      doc.text(`Total Expenses: ${formatCurrency(expense)}`, 15, y); y += 8;
      doc.text(`Net Balance: ${formatCurrency(income - expense)}`, 15, y); y += 8;
      doc.text(`Transaction Count: ${transactions.length}`, 15, y); y += 15;
      transactions.slice(0, 30).forEach(tx => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFontSize(9);
        doc.text(`${new Date(tx.date).toLocaleDateString()} - ${tx.description.substring(0, 40)} - ${tx.type === 'INCOME' ? '+' : '-'}${formatCurrency(tx.amount)}`, 15, y);
        y += 6;
      });
    } else if (reportType === 'inventory') {
      reportTitle = 'Inventory Stock Report';
      doc.setTextColor(50, 50, 50);
      doc.setFontSize(16);
      doc.text(reportTitle, 15, y);
      y += 15;
      doc.setFontSize(11);
      doc.text(`Total Items: ${inventory.length}`, 15, y); y += 8;
      doc.text(`Total Value: ${formatCurrency(inventory.reduce((a, b) => a + b.quantity * (b.costPerUnit || 0), 0))}`, 15, y); y += 15;
      inventory.forEach(item => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFontSize(9);
        doc.text(`${item.productName} - ${item.quantity} ${item.unit} @ ${formatCurrency(item.costPerUnit || 0)} = ${formatCurrency(item.quantity * (item.costPerUnit || 0))}`, 15, y);
        y += 6;
      });
    } else if (reportType === 'staff') {
      reportTitle = 'Staff Directory Report';
      doc.setTextColor(50, 50, 50);
      doc.setFontSize(16);
      doc.text(reportTitle, 15, y);
      y += 15;
      doc.setFontSize(11);
      doc.text(`Total Staff: ${staff.length}`, 15, y); y += 15;
      staff.forEach(s => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFontSize(9);
        doc.text(`${s.name} - ${s.role} - ${s.location} - ${s.status}`, 15, y);
        y += 6;
      });
    } else if (reportType === 'farm') {
      reportTitle = 'Farm Operations Report';
      doc.setTextColor(50, 50, 50);
      doc.setFontSize(16);
      doc.text(reportTitle, 15, y);
      y += 15;
      doc.setFontSize(11);
      doc.text(`Farms: ${farms.length}`, 15, y); y += 8;
      doc.text(`Crops: ${crops.length}`, 15, y); y += 8;
      doc.text(`Harvests: ${harvests.length}`, 15, y); y += 15;
      farms.forEach(f => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(`${f.name} - ${f.location} (${f.size})`, 15, y);
        doc.setFont('helvetica', 'normal');
        y += 7;
      });
    }

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by NEXA AGRI on ${now.toLocaleString()}`, 15, 290);
    
    const fileName = `NexaAgri_${reportType}_${Date.now()}`;
    doc.save(`${fileName}.pdf`);

    // Save to vault
    addDocument({
      id: crypto.randomUUID(),
      name: reportTitle,
      type: 'REPORT',
      category: reportType.charAt(0).toUpperCase() + reportType.slice(1),
      size: '~1MB',
      date: now.toISOString(),
      url: '#',
      uploadedBy: user?.name || 'System'
    } as AppDocument);

    setTimeout(() => {
      setIsGenerating(false);
      setShowGenerateModal(false);
    }, 800);
  };

  const filteredDocs = documents.filter(doc => {
      const matchTab = activeTab === 'ALL' || doc.type === activeTab;
      const matchSearch = doc.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          doc.category.toLowerCase().includes(searchTerm.toLowerCase());
      return matchTab && matchSearch;
  });

  const handleUpload = () => {
    if ((newDoc.name || selectedFile?.name) && newDoc.type) {
        setIsUploading(true);
        const fileName = newDoc.name || selectedFile?.name || 'Untitled Document';
        const fileSize = selectedFile ? (selectedFile.size / (1024 * 1024)).toFixed(1) + 'MB' : '0MB';

        const finalize = (url: string) => {
            addDocument({
                id: crypto.randomUUID(),
                name: fileName,
                type: newDoc.type!,
                category: newDoc.category || 'General',
                size: fileSize,
                date: new Date().toISOString(),
                url,
                uploadedBy: user?.name || 'Authorized Lead'
            } as AppDocument);
            setIsUploading(false);
            setShowUploadModal(false);
            setNewDoc({ type: 'CONTRACT', category: 'General' });
            setSelectedFile(null);
        };

        if (selectedFile) {
            const reader = new FileReader();
            reader.onload = (e) => finalize(e.target?.result as string);
            reader.readAsDataURL(selectedFile);
        } else {
            finalize('#');
        }
    }
  };

  const getIcon = (type: string) => {
      switch(type) {
          case 'CONTRACT': return <FileCheck className="text-emerald-500" />;
          case 'INVOICE': return <DollarSign className="text-blue-500" />;
          case 'RECEIPT': return <FileArchive className="text-amber-500" />;
          case 'REPORT': return <FileStack className="text-purple-500" />;
          default: return <FileText className="text-slate-400" />;
      }
  };

  return (
    <div className="space-y-8 pb-20">
      <div className="flex flex-col md:flex-row justify-between md:items-center gap-6">
        <div>
            <h1 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight leading-none">Corporate Vault</h1>
            <p className="text-slate-500 dark:text-slate-400 font-medium mt-3">High-integrity repository for legal, financial, and operational assets.</p>
        </div>
        <div className="flex space-x-3">
            <button 
                onClick={() => setShowGenerateModal(true)}
                className="bg-slate-900 dark:bg-white text-white dark:text-black px-8 py-4 rounded-[1.5rem] font-black uppercase text-[10px] tracking-[0.2em] shadow-xl active:scale-95 transition-all flex items-center justify-center"
            >
                <Wand2 size={18} className="mr-2" />
                Generate Report
            </button>
            <button 
                onClick={() => setShowUploadModal(true)}
                className="bg-emerald-600 hover:bg-emerald-700 text-white px-8 py-4 rounded-[1.5rem] font-black uppercase text-[10px] tracking-[0.2em] shadow-xl shadow-emerald-500/20 active:scale-95 transition-all flex items-center justify-center"
            >
                <UploadCloud size={18} className="mr-2" />
                Upload Document
            </button>
        </div>
      </div>

      <div className="bg-white dark:bg-slate-900 p-2 rounded-[2rem] shadow-sm border border-slate-100 dark:border-slate-800 flex flex-col lg:flex-row items-center gap-4">
          <div className="flex-1 relative w-full lg:w-auto">
              <Search className="absolute left-6 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
              <input 
                className="w-full pl-14 pr-4 py-4 border-none bg-slate-50 dark:bg-slate-800/50 rounded-[1.5rem] outline-none font-bold shadow-inner"
                placeholder="Find document by signature or category..."
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
              />
          </div>
          <div className="flex space-x-1 p-1 bg-slate-50 dark:bg-slate-800/50 rounded-2xl w-full lg:w-auto overflow-x-auto scrollbar-hide">
              {['ALL', 'CONTRACT', 'INVOICE', 'RECEIPT', 'REPORT'].map(tab => (
                  <button 
                    key={tab} 
                    onClick={() => setActiveTab(tab as any)}
                    className={`px-6 py-2.5 text-[9px] font-black uppercase tracking-widest rounded-xl transition-all whitespace-nowrap ${activeTab === tab ? 'bg-white dark:bg-slate-700 text-emerald-600 shadow-sm' : 'text-slate-400 hover:text-slate-600'}`}
                  >
                      {tab === 'ALL' ? 'Everything' : tab + 's'}
                  </button>
              ))}
          </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-5">
          {filteredDocs.length === 0 ? (
              <div className="col-span-full py-16 md:py-24 text-center bg-white dark:bg-slate-900 rounded-2xl md:rounded-[2.5rem] border-2 border-dashed border-slate-100 dark:border-slate-800">
                  <div className="w-16 h-16 bg-slate-50 dark:bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-4">
                    <FileStack size={32} className="text-slate-200 dark:text-slate-700" />
                  </div>
                  <p className="text-slate-400 font-black uppercase tracking-[0.2em] text-xs">No Documents Found</p>
              </div>
          ) : filteredDocs.map(doc => (
              <div key={doc.id} className="bg-white dark:bg-slate-900 p-5 md:p-6 rounded-2xl border border-slate-100 dark:border-slate-800 shadow-sm hover:shadow-xl transition-all group flex flex-col justify-between">
                  <div>
                    <div className="flex justify-between items-start mb-4">
                        <div className="w-11 h-11 bg-slate-50 dark:bg-slate-800 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform shadow-inner">
                            {getIcon(doc.type)}
                        </div>
                        <div className="flex space-x-1">
                            <button onClick={() => setPreviewDoc(doc)} className="p-2 text-slate-400 hover:text-blue-500 bg-slate-50 dark:bg-slate-800 rounded-lg transition-all" title="Preview"><Eye size={14}/></button>
                            <button onClick={() => deleteDocument(doc.id)} className="p-2 text-slate-400 hover:text-red-500 bg-slate-50 dark:bg-slate-800 rounded-lg transition-all" title="Delete"><Trash2 size={14}/></button>
                        </div>
                    </div>
                    <h3 className="font-black text-slate-800 dark:text-white text-sm line-clamp-2 leading-snug mb-2">{doc.name}</h3>
                    <div className="flex items-center space-x-2 mb-5">
                        <span className="text-[8px] font-black uppercase tracking-widest bg-emerald-50 dark:bg-emerald-900/20 px-2 py-0.5 rounded text-emerald-600 border border-emerald-100 dark:border-emerald-800/50">{doc.type}</span>
                        <span className="text-[8px] font-black uppercase tracking-widest text-slate-400">{doc.size}</span>
                    </div>
                  </div>

                  <div className="pt-4 border-t border-slate-50 dark:border-slate-800 flex justify-between items-center">
                      <div className="space-y-0.5">
                        <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest flex items-center">
                            <Plus size={10} className="mr-1 text-emerald-500" /> {doc.uploadedBy.split(' ')[0]}
                        </p>
                        <p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest">
                            {new Date(doc.date).toLocaleDateString()}
                        </p>
                      </div>
                      <button
                        className="bg-slate-900 dark:bg-white text-white dark:text-black p-2.5 rounded-lg hover:scale-110 active:scale-90 transition-all shadow-lg"
                        title="Download"
                        onClick={() => {
                          if (doc.url && doc.url !== '#') {
                            const a = document.createElement('a');
                            a.href = doc.url;
                            a.download = doc.name;
                            document.body.appendChild(a);
                            a.click();
                            document.body.removeChild(a);
                          } else {
                            const content = `Document: ${doc.name}\nType: ${doc.type}\nCategory: ${doc.category}\nDate: ${new Date(doc.date).toLocaleDateString()}\nUploaded by: ${doc.uploadedBy}`;
                            const blob = new Blob([content], { type: 'text/plain' });
                            const url = URL.createObjectURL(blob);
                            const a = document.createElement('a');
                            a.href = url;
                            a.download = `${doc.name}.txt`;
                            document.body.appendChild(a);
                            a.click();
                            document.body.removeChild(a);
                            URL.revokeObjectURL(url);
                          }
                        }}
                      >
                          <Download size={14} />
                      </button>
                  </div>
              </div>
          ))}
      </div>

      {/* PREVIEW MODAL */}
      {previewDoc && (
          <div className="fixed inset-0 bg-slate-950/95 flex items-center justify-center z-[200] p-3 md:p-8 backdrop-blur-xl animate-in zoom-in duration-300">
               <div className="bg-white dark:bg-slate-900 rounded-2xl md:rounded-[2rem] w-full max-w-4xl h-[85vh] shadow-2xl flex flex-col overflow-hidden border border-white/10">
                    <div className="p-4 md:p-6 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-900/50">
                        <div className="flex items-center space-x-3 md:space-x-5 min-w-0">
                            <div className="w-10 h-10 bg-white dark:bg-slate-800 rounded-xl flex items-center justify-center text-emerald-500 shadow-sm border dark:border-slate-700 shrink-0">
                                {getIcon(previewDoc.type)}
                            </div>
                            <div className="min-w-0">
                                <h3 className="text-sm md:text-lg font-black text-slate-900 dark:text-white leading-none truncate">{previewDoc.name}</h3>
                                <p className="text-[8px] md:text-[9px] font-black text-slate-400 uppercase tracking-widest mt-1">{previewDoc.type} - {previewDoc.size}</p>
                            </div>
                        </div>
                        <button onClick={() => setPreviewDoc(null)} className="w-10 h-10 rounded-full bg-white dark:bg-slate-800 flex items-center justify-center text-slate-400 hover:rotate-90 transition-all shadow-sm border dark:border-slate-700 shrink-0"><X size={20}/></button>
                    </div>
                    <div className="flex-1 bg-slate-100 dark:bg-slate-950 p-4 md:p-8 flex items-center justify-center overflow-auto">
                        <div className="w-full max-w-2xl bg-white dark:bg-slate-900 p-8 md:p-14 rounded-2xl shadow-xl space-y-8 border dark:border-slate-800">
                            <div className="h-4 w-2/3 bg-slate-100 dark:bg-slate-800 rounded-full" />
                            <div className="space-y-3">
                                <div className="h-3 w-full bg-slate-50 dark:bg-slate-800/50 rounded-full" />
                                <div className="h-3 w-full bg-slate-50 dark:bg-slate-800/50 rounded-full" />
                                <div className="h-3 w-4/5 bg-slate-50 dark:bg-slate-800/50 rounded-full" />
                            </div>
                            <div className="h-32 w-full bg-slate-50 dark:bg-slate-800/30 rounded-xl border border-dashed border-slate-200 dark:border-slate-800 flex items-center justify-center">
                                <FileText size={40} className="text-slate-200 dark:text-slate-800" />
                            </div>
                            <p className="text-center text-[10px] font-black text-slate-400 uppercase tracking-widest italic pt-6">Document Preview</p>
                        </div>
                    </div>
               </div>
          </div>
      )}

      {/* UPLOAD MODAL */}
      {showUploadModal && (
          <div className="fixed inset-0 bg-slate-950/90 flex items-center justify-center z-[150] p-3 md:p-4 backdrop-blur-xl animate-in fade-in duration-300">
              <div className="bg-white dark:bg-slate-900 rounded-2xl md:rounded-[2.5rem] w-full max-w-lg md:max-w-xl shadow-2xl overflow-hidden border border-white/10 flex flex-col max-h-[90vh]">
                  <div className="p-5 md:p-8 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-900/50">
                    <div>
                        <h3 className="text-xl md:text-2xl font-black text-slate-900 dark:text-white tracking-tight leading-none">Upload Document</h3>
                        <p className="text-slate-500 mt-1 font-medium text-xs md:text-sm">Secure file upload with indexing.</p>
                    </div>
                    <button onClick={() => { setShowUploadModal(false); setSelectedFile(null); }} className="w-9 h-9 md:w-11 md:h-11 rounded-full bg-white dark:bg-slate-800 border flex items-center justify-center text-slate-400 hover:rotate-90 transition-all shadow-sm shrink-0"><X size={20}/></button>
                  </div>
                  
                  <div className="p-5 md:p-8 space-y-5 md:space-y-6 overflow-y-auto">
                      <input 
                        type="file" 
                        ref={fileInputRef}
                        className="hidden"
                        accept=".pdf,.doc,.docx,.xlsx,.xls,.jpg,.jpeg,.png,.gif,.csv,.txt"
                        onChange={e => {
                          const file = e.target.files?.[0];
                          if (file) {
                            setSelectedFile(file);
                            if (!newDoc.name) setNewDoc({...newDoc, name: file.name});
                          }
                        }}
                      />
                      <div 
                        onClick={() => fileInputRef.current?.click()}
                        className="border-2 border-dashed border-slate-200 dark:border-slate-700 rounded-2xl p-6 md:p-8 text-center bg-slate-50/30 dark:bg-slate-800/30 hover:bg-slate-50 transition-all cursor-pointer group shadow-inner"
                      >
                           {selectedFile ? (
                             <div className="flex flex-col items-center">
                               <CheckCircle2 size={36} className="text-emerald-500 mb-3" />
                               <p className="text-sm font-black text-emerald-600 uppercase tracking-widest">{selectedFile.name}</p>
                               <p className="text-[10px] text-slate-400 mt-1 font-medium">{(selectedFile.size / (1024 * 1024)).toFixed(1)} MB - Click to change</p>
                             </div>
                           ) : (
                             <>
                               <UploadCloud size={36} className="mx-auto text-slate-300 group-hover:text-emerald-600 transition-colors mb-3" />
                               <p className="text-sm font-black text-slate-500 uppercase tracking-widest">Select File to Upload</p>
                               <p className="text-[10px] text-slate-400 mt-1 font-medium">PDF, DOCX, XLSX, JPG, PNG (Max: 50MB)</p>
                             </>
                           )}
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div className="space-y-1.5">
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] px-2 block">Document Name</label>
                              <input 
                                className="w-full border-none bg-slate-50 dark:bg-slate-800 p-4 rounded-xl dark:text-white font-bold outline-none focus:ring-4 focus:ring-emerald-500/10 shadow-inner text-sm"
                                placeholder="e.g. Q4 Logistics Report"
                                value={newDoc.name || ''}
                                onChange={e => setNewDoc({...newDoc, name: e.target.value})}
                              />
                          </div>
                          <div className="space-y-1.5">
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] px-2 block">Classification</label>
                              <select 
                                className="w-full border-none bg-slate-50 dark:bg-slate-800 p-4 rounded-xl dark:text-white font-bold outline-none focus:ring-4 focus:ring-emerald-500/10 shadow-inner uppercase tracking-widest text-[10px]"
                                value={newDoc.type}
                                onChange={e => setNewDoc({...newDoc, type: e.target.value as any})}
                              >
                                  <option value="CONTRACT">Legal Contract</option>
                                  <option value="INVOICE">Invoice</option>
                                  <option value="RECEIPT">Receipt</option>
                                  <option value="REPORT">Report</option>
                                  <option value="DOWNLOAD">Download</option>
                              </select>
                          </div>
                      </div>
                  </div>

                  <div className="p-5 md:p-8 border-t border-slate-100 dark:border-slate-800 flex justify-end space-x-3 bg-slate-50/50 dark:bg-slate-900/50">
                      <button onClick={() => { setShowUploadModal(false); setSelectedFile(null); }} className="px-6 md:px-8 py-3 md:py-4 text-slate-500 font-black uppercase tracking-widest hover:bg-slate-100 rounded-xl md:rounded-2xl transition-all text-[10px]">Cancel</button>
                      <button 
                        onClick={handleUpload}
                        disabled={isUploading || (!newDoc.name && !selectedFile)}
                        className="px-8 md:px-10 py-3 md:py-4 bg-emerald-600 text-white rounded-xl md:rounded-2xl font-black uppercase tracking-[0.15em] shadow-xl active:scale-95 transition-all text-[10px] flex items-center justify-center disabled:opacity-50"
                      >
                          {isUploading ? (
                              <><RefreshCw className="animate-spin mr-2" size={16} /> Uploading...</>
                          ) : (
                              <>Upload <CheckCircle2 size={16} className="ml-2" /></>
                          )}
                      </button>
                  </div>
              </div>
          </div>
      )}

      {/* GENERATE REPORT MODAL */}
      {showGenerateModal && (
        <div className="fixed inset-0 bg-slate-950/90 flex items-center justify-center z-[150] p-3 md:p-4 backdrop-blur-xl animate-in zoom-in duration-300">
          <div className="bg-white dark:bg-slate-900 rounded-2xl md:rounded-[2.5rem] w-full max-w-md shadow-2xl overflow-hidden border border-white/10 max-h-[90vh] flex flex-col">
            <div className="p-5 md:p-8 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-900/50">
              <div>
                <h3 className="text-xl md:text-2xl font-black text-slate-900 dark:text-white tracking-tight">Generate Report</h3>
                <p className="text-slate-500 mt-1 font-medium text-xs md:text-sm">Create a PDF from your data</p>
              </div>
              <button onClick={() => setShowGenerateModal(false)} className="w-9 h-9 md:w-11 md:h-11 rounded-full bg-white dark:bg-slate-800 border flex items-center justify-center text-slate-400 hover:rotate-90 transition-all shadow-sm shrink-0"><X size={20}/></button>
            </div>
            <div className="p-4 md:p-6 space-y-3 overflow-y-auto">
              {[
                { id: 'financial', title: 'Financial Summary', desc: 'Income, expenses, and transaction history', icon: <DollarSign size={20} className="text-emerald-500" />, count: `${transactions.length} transactions` },
                { id: 'inventory', title: 'Inventory Report', desc: 'Stock levels, valuations, and item list', icon: <Package size={20} className="text-blue-500" />, count: `${inventory.length} items` },
                { id: 'staff', title: 'Staff Directory', desc: 'Team members, roles, and assignments', icon: <Users size={20} className="text-purple-500" />, count: `${staff.length} members` },
                { id: 'farm', title: 'Farm Operations', desc: 'Farms, crops, and harvest data', icon: <TrendingUp size={20} className="text-amber-500" />, count: `${farms.length} farms` },
              ].map(report => (
                <button
                  key={report.id}
                  onClick={() => generateReport(report.id)}
                  disabled={isGenerating}
                  className="w-full flex items-center space-x-4 p-4 md:p-5 bg-slate-50 dark:bg-slate-800/50 rounded-xl md:rounded-2xl border border-slate-100 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 transition-all text-left group disabled:opacity-50"
                >
                  <div className="w-10 h-10 bg-white dark:bg-slate-900 rounded-lg flex items-center justify-center shadow-sm group-hover:scale-110 transition-transform shrink-0">
                    {report.icon}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-black text-sm text-slate-900 dark:text-white">{report.title}</p>
                    <p className="text-[10px] text-slate-400 mt-0.5">{report.desc}</p>
                  </div>
                  <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest whitespace-nowrap">{report.count}</span>
                </button>
              ))}
              {isGenerating && (
                <div className="flex items-center justify-center py-4 text-emerald-600">
                  <RefreshCw className="animate-spin mr-2" size={16} />
                  <span className="text-[10px] font-black uppercase tracking-widest">Generating PDF...</span>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
